version: "3.9"

services:
  backend:
    container_name: contest-backend
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  postgres:
    container_name: contest-postgres
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: contest_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
